#!/usr/bin/env bash
set -euo pipefail
shopt -s nullglob

user_pubs=(keys/aly_*.pub)
host_pubs=(keys/root_*.pub)

{
    cat <<'EOF'
# Auto-generated by `just sops-rekey` from keys/*.pub.
# Every recipient can decrypt every secret. To add or remove a
# machine, add or remove its .pub file and re-run `just sops-rekey`.
keys:
  # === user keys (aly@<host>) ===
EOF
    for f in "${user_pubs[@]}"
    do
        host=$(basename "$f" .pub)
        host=${host#aly_}
        age=$(ssh-to-age -i "$f")
        printf '  - &user_aly_%s %s\n' "$host" "$age"
    done
    echo "  # === host keys (root@<host>) ==="
    for f in "${host_pubs[@]}"
    do
        host=$(basename "$f" .pub)
        host=${host#root_}
        age=$(ssh-to-age -i "$f")
        printf '  - &host_%s %s\n' "$host" "$age"
    done
    cat <<'EOF'

creation_rules:
  - path_regex: ^secrets/.*\.ya?ml$
    key_groups:
      - age:
EOF
    for f in "${user_pubs[@]}"
    do
        host=$(basename "$f" .pub)
        host=${host#aly_}
        printf '          - *user_aly_%s\n' "$host"
    done
    for f in "${host_pubs[@]}"
    do
        host=$(basename "$f" .pub)
        host=${host#root_}
        printf '          - *host_%s\n' "$host"
    done
} > .sops.yaml
echo "regenerated .sops.yaml"

for f in secrets/*.yaml
do
    echo "rekeying $f"
    sops updatekeys -y "$f"
done
