rootPasswordHash: ENC[AES256_GCM,data:TgH9Ee8EiTdVMHcbqkvMmX9DMDmuXOBeTizAADx32nIWmgQchScDnkQ6gXh3vBNnIV8v/E3MKXWqVwr8yRPepXgNf/4LqLXxD5d5/rDSNubtygqYISgq7+qexBSlMWNPd/FORhavdTeKG74=,iv:li0ACYoolvG+3qxWBy5IhmxU21tToiFPj9YIkr7npvM=,tag:IdiAQ0md9cfLIm1chPwouQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrYWlVYmsrMHhVZlJvNHlq
            Q1kzQ3drb1k1UmlTMDV1MFM2L0p1anAwR2gwCng3S2VpWlRwTy9SNENXK21qSzVs
            RUx4KzJEYlovQjNCQTFoS3RUOXRKRWsKLS0tIGFaSWtjLzc3VlRuOGVTQXRSSG56
            OWcxanN5S2hVdVltNUZOYXRuQ3cvdjAK40PpXXsPWSZkWNoiL8kDnixztC/QaFmY
            N0wZm4CaFcIUPafcIShG9pvSwRLpunoon812If8UalDaAx0RNAgzNQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvMUs0aGtOQjdQclVKKzdG
            Z2F0NVpaUjU3a0JYa2E0TlJsaExHNmJEY1RZCkNwZ3hkY2tSaGIwSEI0eVI4TUVW
            amN6bnVrT2hQVWxQakMwQ2pESmk3YUkKLS0tIE1Cdm5XR0NQZ3hQRTgxUFJJZFNr
            RU5UN2tlRysxWTNDcUowbUpmdGxwYXcKzcTv9slDub8qNOENr0gxi2F4INzuuGmd
            G6zSKFEHiq+XY106PXMAygJ3kLtf+9j7hhPWaZ4TaYNMR5G58xUzsA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195amyw68uu4g9cztq55zyy4747nu8dzy3h0lfj72wqhrlasq0sgqse4tas
    lastmodified: "2026-06-28T20:45:15Z"
    mac: ENC[AES256_GCM,data:xQ4SnR7L97ebNtU47MQ5NCNmEnqZCvyGt6LlWO6qc8i57sE7SFizqMOlIEB5GOg77vmxWj0snIiKUu71y1rmn9NkWrXOmZ9SL/6Tvx35c9f37ClYdOykm3vOVeLQ01PDjzQHMlA4UqxkO+tF7/0pZi1RwFxtFwvBM+YV+qd8IBs=,iv:ecQCD5kJsOzFChkD/lB6Sts11Jxy1o9BjtT4d/N+K+o=,tag:6W0xWT896MsiGJps4F+eeg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
